/*
 * Engines API
 *
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo],v1:[fiab]
 * Contact: api@factset.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FactSet.AnalyticsAPI.Engines.Client.OpenAPIDateConverter;

namespace FactSet.AnalyticsAPI.Engines.Model
{
    /// <summary>
    /// EventSummary
    /// </summary>
    [DataContract(Name = "EventSummary")]
    public partial class EventSummary : IEquatable<EventSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSummary" /> class.
        /// </summary>
        /// <param name="message">Event&#39;s message.</param>
        /// <param name="submissiondatetime">Event&#39;s submission time.</param>
        /// <param name="type">Event&#39;s type.</param>
        public EventSummary(string message = default(string), DateTime submissiondatetime = default(DateTime), string type = default(string))
        {
            this.Message = message;
            this.Submissiondatetime = submissiondatetime;
            this.Type = type;
        }

        /// <summary>
        /// Event&#39;s message
        /// </summary>
        /// <value>Event&#39;s message</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Event&#39;s submission time
        /// </summary>
        /// <value>Event&#39;s submission time</value>
        [DataMember(Name = "submissiondatetime", EmitDefaultValue = false)]
        public DateTime Submissiondatetime { get; set; }

        /// <summary>
        /// Event&#39;s type
        /// </summary>
        /// <value>Event&#39;s type</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventSummary {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Submissiondatetime: ").Append(Submissiondatetime).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EventSummary);
        }

        /// <summary>
        /// Returns true if EventSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of EventSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Submissiondatetime == input.Submissiondatetime ||
                    (this.Submissiondatetime != null &&
                    this.Submissiondatetime.Equals(input.Submissiondatetime))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.Submissiondatetime != null)
                    hashCode = hashCode * 59 + this.Submissiondatetime.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
