/*
 * Engines API
 *
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: analytics.api.support@factset.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FactSet.AnalyticsAPI.Engines.Client.OpenAPIDateConverter;

namespace FactSet.AnalyticsAPI.Engines.Model
{
    /// <summary>
    /// QuantAllUniversalScreenParameters
    /// </summary>
    [DataContract(Name = "QuantAllUniversalScreenParameters")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    public partial class QuantAllUniversalScreenParameters : QuantFormula, IEquatable<QuantAllUniversalScreenParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuantAllUniversalScreenParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QuantAllUniversalScreenParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuantAllUniversalScreenParameters" /> class.
        /// </summary>
        /// <param name="type">type (required) (default to &quot;QuantAllUniversalScreenParameters&quot;).</param>
        /// <param name="source">source (required).</param>
        public QuantAllUniversalScreenParameters(string type = "QuantAllUniversalScreenParameters", SourceEnum source = default(SourceEnum)) : base(type, source)
        {
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QuantAllUniversalScreenParameters {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuantAllUniversalScreenParameters);
        }

        /// <summary>
        /// Returns true if QuantAllUniversalScreenParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of QuantAllUniversalScreenParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuantAllUniversalScreenParameters input)
        {
            if (input == null)
                return false;

            return base.Equals(input);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
