/*
 * Engines API
 *
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: analytics.api.support@factset.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FactSet.AnalyticsAPI.Engines.Client.OpenAPIDateConverter;

namespace FactSet.AnalyticsAPI.Engines.Model
{
    /// <summary>
    /// QuantDate
    /// </summary>
    [DataContract(Name = "QuantDate")]
    public partial class QuantDate : IEquatable<QuantDate>, IValidatableObject
    {
        /// <summary>
        /// Defines ClassName
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ClassNameEnum
        {
            /// <summary>
            /// Enum FdsDate for value: FdsDate
            /// </summary>
            [EnumMember(Value = "FdsDate")]
            FdsDate = 1,

            /// <summary>
            /// Enum DateList for value: DateList
            /// </summary>
            [EnumMember(Value = "DateList")]
            DateList = 2

        }


        /// <summary>
        /// Gets or Sets ClassName
        /// </summary>
        [DataMember(Name = "className", IsRequired = true, EmitDefaultValue = false)]
        public ClassNameEnum ClassName { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuantDate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QuantDate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuantDate" /> class.
        /// </summary>
        /// <param name="className">className (required).</param>
        /// <param name="frequency">frequency (required).</param>
        /// <param name="calendar">calendar (required).</param>
        public QuantDate(ClassNameEnum className = default(ClassNameEnum), string frequency = default(string), string calendar = default(string))
        {
            this.ClassName = className;
            // to ensure "frequency" is required (not null)
            if (frequency == null) {
                throw new ArgumentNullException("frequency is a required property for QuantDate and cannot be null");
            }
            this.Frequency = frequency;
            // to ensure "calendar" is required (not null)
            if (calendar == null) {
                throw new ArgumentNullException("calendar is a required property for QuantDate and cannot be null");
            }
            this.Calendar = calendar;
        }

        /// <summary>
        /// Gets or Sets Frequency
        /// </summary>
        [DataMember(Name = "frequency", IsRequired = true, EmitDefaultValue = false)]
        public string Frequency { get; set; }

        /// <summary>
        /// Gets or Sets Calendar
        /// </summary>
        [DataMember(Name = "calendar", IsRequired = true, EmitDefaultValue = false)]
        public string Calendar { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QuantDate {\n");
            sb.Append("  ClassName: ").Append(ClassName).Append("\n");
            sb.Append("  Frequency: ").Append(Frequency).Append("\n");
            sb.Append("  Calendar: ").Append(Calendar).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuantDate);
        }

        /// <summary>
        /// Returns true if QuantDate instances are equal
        /// </summary>
        /// <param name="input">Instance of QuantDate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuantDate input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ClassName == input.ClassName ||
                    this.ClassName.Equals(input.ClassName)
                ) && 
                (
                    this.Frequency == input.Frequency ||
                    (this.Frequency != null &&
                    this.Frequency.Equals(input.Frequency))
                ) && 
                (
                    this.Calendar == input.Calendar ||
                    (this.Calendar != null &&
                    this.Calendar.Equals(input.Calendar))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ClassName.GetHashCode();
                if (this.Frequency != null)
                {
                    hashCode = (hashCode * 59) + this.Frequency.GetHashCode();
                }
                if (this.Calendar != null)
                {
                    hashCode = (hashCode * 59) + this.Calendar.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
