/*
 * Engines API
 *
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,security-modeling,others],v1:[fiab]
 * Contact: api@factset.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FactSet.AnalyticsAPI.Engines.Client.OpenAPIDateConverter;

namespace FactSet.AnalyticsAPI.Engines.Model
{
    /// <summary>
    /// SMTemplateFieldProperties
    /// </summary>
    [DataContract(Name = "SMTemplateFieldProperties")]
    public partial class SMTemplateFieldProperties : IEquatable<SMTemplateFieldProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SMTemplateFieldProperties" /> class.
        /// </summary>
        /// <param name="category">category.</param>
        /// <param name="mandatory">mandatory.</param>
        /// <param name="whenField">whenField.</param>
        public SMTemplateFieldProperties(List<string> category = default(List<string>), bool mandatory = default(bool), List<Dictionary<string, List<string>>> whenField = default(List<Dictionary<string, List<string>>>))
        {
            this.Category = category;
            this.Mandatory = mandatory;
            this.WhenField = whenField;
        }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public List<string> Category { get; set; }

        /// <summary>
        /// Gets or Sets Mandatory
        /// </summary>
        [DataMember(Name = "mandatory", EmitDefaultValue = false)]
        public bool Mandatory { get; set; }

        /// <summary>
        /// Gets or Sets WhenField
        /// </summary>
        [DataMember(Name = "whenField", EmitDefaultValue = false)]
        public List<Dictionary<string, List<string>>> WhenField { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SMTemplateFieldProperties {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Mandatory: ").Append(Mandatory).Append("\n");
            sb.Append("  WhenField: ").Append(WhenField).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SMTemplateFieldProperties);
        }

        /// <summary>
        /// Returns true if SMTemplateFieldProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of SMTemplateFieldProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SMTemplateFieldProperties input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Category == input.Category ||
                    this.Category != null &&
                    input.Category != null &&
                    this.Category.SequenceEqual(input.Category)
                ) && 
                (
                    this.Mandatory == input.Mandatory ||
                    this.Mandatory.Equals(input.Mandatory)
                ) && 
                (
                    this.WhenField == input.WhenField ||
                    this.WhenField != null &&
                    input.WhenField != null &&
                    this.WhenField.SequenceEqual(input.WhenField)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                hashCode = hashCode * 59 + this.Mandatory.GetHashCode();
                if (this.WhenField != null)
                    hashCode = hashCode * 59 + this.WhenField.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
